# Generated by Django 5.1.2 on 2024-10-26 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_url', models.URLField()),
                ('image_url', models.URLField()),
                ('languages', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('enroll_count', models.CharField(blank=True, max_length=50)),
                ('old_price', models.CharField(blank=True, max_length=50)),
                ('new_price', models.CharField(blank=True, max_length=50)),
                ('free_code_url', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
